### ISSUE TITLE
enable var.x application

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OISSTv3#37]
add var.x to the ctests
- use `BUMP` covariance in the yaml
- use the sample observations that are already in this repository

**Comment by loganchen39** [comment]
@travissluka I have uploaded some source/yaml files for this issue. Please help check the "var.yml", and pay attention to my comments which are from test results. 

Currently the test_umdsst_var failed due to error message 
"LinearGetValues::setTrajectory,unkown state variable"
which is from file LinearGetValues.cc, function 
void LinearGetValues::setTrajectory(const State & state, const util::DateTime & t1, const util::DateTime & t2, ufo::GeoVaLs & geovals)
where "In LinearGetValues::setTrajectory(), i = 0, vars[i] = air_pressure_levels", which is not equal to sea_surface_temperature. Not sure how this "ufo::GeoVaLs & geovals" get this vars[0] = air_pressure_levels. I'm using grep to check its origin. 

Let me know if you have any clue or suggestions.

**Comment by travissluka** [comment]
you're using the wrong observation operator. it should be `Identity`. also the covariance model for the observation should be `diagonal`. I'm not sure where `obs type` came from, remove it

Make your window length 24 hours, and the background date at 12Z, otherwise i think a large number of the test observations will be removed. the `variational...increment.date` should be the same as the background date

**Comment by loganchen39** [comment]
@travissluka Now it can run, but the result increment and those cost functions are like missing values. Could it be related to issues #38 ~ #40? Should I finish these rest issues and then come back to this one? Also please help check my new var.yml on github at branch feature/var.x. Below are some output to give you an idea what's wrong.


11:   Quadratic cost function: J   ( 4) = 5.062988689257226e+78
11:   Quadratic cost function: Jb  ( 4) = 5.071143924289982e+77
11:   Quadratic cost function: JoJc( 4) = 4.555874296828227e+78
......
11: Write Increment: done.
11: CostFunction::addIncrement: First guess:min = -1.79001, max = 31.8058, mean = 13.1571
11: umdsst::ModelAuxControl not implemented
11:
11: CostFunction::addIncrement: Increment:min = -2.31779e+38, max = 4.54771e+38, mean = 1.87764e+37
11: umdsst::ModelAuxIncrement not implemented
11:
11: CostFunction::addIncrement: Analysis: min = -2.31779e+38, max = 3.78795e+38, mean = 2.65433e+36
11: umdsst::ModelAuxControl not implemented
11:
11: Test     : CostFunction::addIncrement: Analysis: min = -2.31779e+38, max = 3.78795e+38, mean = 2.65433e+36
11: Test     : umdsst::ModelAuxControl not implemented
11:
11: Variational: incremental assimilation done 1 iterations.
11: In Fields::write(), missing_ = -3.33477e+38

**Comment by travissluka** [comment]
Yes, the missing values are causing problems.
What you can do is add a `background check` QC filter to the yaml file. (see https://github.com/JCSDA-internal/soca/blob/504cf79ecd216528be17d300c2a829c8aa14a62e/test/testinput/3dvar_soca.yml#L115-116 for an example) which will remove any observation where the interpolation is messed up. This should let you get a "working" 3dvar where the analysis doesn't look completely crazy (yay!) before we move on to making it work "correctly".
