### ISSUE TITLE
get a better landmask

### ISSUE THREAD

**Issue by travissluka** [UMD-AOSC/OISSTv3#61]
- Replace landmask file with a better one (mainly fixing Central America).
- make sure there are observations in the dirac test that are near Panama so that the network check on the land mask can be properly tested.

**Comment by loganchen39** [comment]
@travissluka  I uploaded an improved landmask.nc then the test of test_umdsst_staticbinit failed due to 
"Level   1: 0% 5% 10% 15% 20% 25% 30% 35% 40% 45% 50% 55% 60%!!! ABORT in mpl_nc_dim_define_or_get on task #0002: dimension nc1b has a different size in file".
Those files that have "nc1b" are bump/bump_sst_nicas_000002-000001.nc and bump/bump_sst_nicas_000002-000002.nc, and the nc1b values in these two files are 1049 and 841 respectively. 

If I use the original landmask, all of the tests can pass. What might be the problem?

**Comment by loganchen39** [comment]
@travissluka The improved landmask is at the feature/betterLandmask branch.

**Comment by travissluka** [comment]
oops, I had said the bump files should be deleted before staticbinit is run, but it turns out i forgot the ` rm -f $f ` line after https://github.com/UMD-AOSC/UMD-SST/blob/89c45319844aaa3e05c47732832816232d9441dd/test/test_wrapper.sh#L13, so the files are not actually being deleted. If you fix that it might fix the problem.

I'm away from home this week, but I can take a closer look when I get back tuesday.

**Comment by travissluka** [comment]
closed by https://github.com/UMD-AOSC/UMD-SST/pull/63
